version: 0.2

phases:
  install:
    commands:
       - echo "install phase"
  pre_build:
    commands:
       - echo "pre_build phase"
  build:
    commands:
       - echo "build phase"
       - ls
       - aws cloudformation package --template-file etl-covid19-cloudformation.yml --s3-bucket cloud-guru-challenge-etl-lambda-code-rahul --output-template-file output.yml  
       - ls
artifacts:
  type: zip
  files:
    - output.yml
  secondary-artifacts:
    OutPutPackageFile:
      files:
        - output.yml